copyright: Copyright &copy; 2023 Mirascope, Inc.
site_name: Mirascope
site_url: https://docs.mirascope.io/
site_description: Mirascope is an open-source library for the most pythonic LLM application building experience.
repo_name: mirascope
repo_url: https://github.com/Mirascope/mirascope/
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotation
    - content.code.copy
    - content.code.link
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: indigo
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mirascope
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/WilliamBakst
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wbakst/
  analytics:
    provider: google
    property: G-DJHT1QG9GK

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

plugins:
  - mike:
      alias_type: symlink
      canonical_version: latest
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: false
            docstring_style: google

nav:
  - Get Started:
      - Mirascope: "README.md"
      - Contributing: "CONTRIBUTING.md"
      - How to help: "HELP.md"
  - Concepts:
      - Writing Prompts: "concepts/writing_prompts.md"
      - Generating content: "concepts/generating_content.md"
      - Streaming generated content: "concepts/streaming_generated_content.md"
      - Using different model providers: "concepts/using_different_model_providers.md"
      - Using the Mirascope CLI: "concepts/using_the_mirascope_cli.md"
      - Extracting structured information using LLMs: "concepts/extracting_structured_information_using_llms.md"
      - Defining and extracting schemas: "concepts/defining_and_extracting_schemas.md"
      - Extracting base types: "concepts/extracting_base_types.md"
      - Validation: "concepts/validation.md"
      - Tools (Function Calling): "concepts/tools_(function_calling).md"
      - Defining tools (function calls): "concepts/defining_tools_(function_calls).md"
      - Attaching and calling tool functions: "concepts/attaching_and_calling_tool_functions.md"
      - Dumping prompts and calls: "concepts/dumping_prompts_and_calls.md"
      - Integrations: "concepts/integrations.md"
  - Cookbook: "cookbook/index.md"
  - API Reference:
      - "api/index.md"
      - anthropic:
          - "api/anthropic/index.md"
          - calls: "api/anthropic/calls.md"
          - extractors: "api/anthropic/extractors.md"
          - tools: "api/anthropic/tools.md"
          - types: "api/anthropic/types.md"
      - base:
          - "api/base/index.md"
          - calls: "api/base/calls.md"
          - extractors: "api/base/extractors.md"
          - prompts: "api/base/prompts.md"
          - tools: "api/base/tools.md"
          - types: "api/base/types.md"
          - utils: "api/base/utils.md"
      - cli:
          - "api/cli/index.md"
          - commands: "api/cli/commands.md"
          - constants: "api/cli/constants.md"
          - generic: "api/cli/generic.md"
          - schemas: "api/cli/schemas.md"
          - utils: "api/cli/utils.md"
      - enums: "api/enums.md"
      - gemini:
          - "api/gemini/index.md"
          - calls: "api/gemini/calls.md"
          - extractors: "api/gemini/extractors.md"
          - tools: "api/gemini/tools.md"
          - types: "api/gemini/types.md"
      - mistral:
          - "api/mistral/index.md"
          - calls: "api/mistral/calls.md"
          - extractors: "api/mistral/extractors.md"
          - tools: "api/mistral/tools.md"
          - types: "api/mistral/types.md"
      - openai:
          - "api/openai/index.md"
          - calls: "api/openai/calls.md"
          - extractors: "api/openai/extractors.md"
          - tools: "api/openai/tools.md"
          - types: "api/openai/types.md"
      - wandb:
          - "api/wandb.md"
